In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("SPECIAL REPORT ON IMPACT OF FLOODS IN MALAYSIA, 2025.xlsx",
                   sheet_name = "Jadual 3.1",
                   skiprows=8)

In [3]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,Johor,NaN,0.000,0.0,NaN,724.6190,719.935,NaN,1634.746,...,0.0,NaN,18.000,0.0,NaN,0.00,0.0,NaN,2429.7150,13010.384
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Kedah,NaN,117473.688,0.0,NaN,346.8500,222.850,NaN,27.115,...,0.0,NaN,4.332,0.0,NaN,89.33,0.0,NaN,118210.0300,5039.940
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Kelantan,NaN,10374.332,0.0,NaN,8544.4495,2322.990,NaN,1020.400,...,0.0,NaN,346.000,4.1,NaN,0.00,0.0,NaN,22443.9795,4383.692

In [4]:
category_cols = ['Paddy', 'Crops', 'Fisheries','Livestock','Fisherman','Agro-entrepreneur', 'High Value Commodity', 'Total Loss']

In [5]:
cols_2024 = [1,3,6,9,12,15,18,21,24]
cols_2025= [1,4,7,10,13,16,19,22,25]

In [6]:
df_2024 = df.iloc[:, cols_2024].copy()
df_2024.columns = ['State'] + category_cols
df_2024['Year'] = 2024

In [7]:
df_2025 = df.iloc[:, cols_2025].copy()
df_2025.columns = ['State'] + category_cols
df_2025['Year'] = 2025

In [8]:
df_2024.head()
df_2025.head()

,State,Paddy,Crops,Fisheries,Livestock,Fisherman,Agro-entrepreneur,High Value Commodity,Total Loss,Year
0,Johor,0.0,719.935,12236.12,54.329,0.0,0.0,0.0,13010.384,2025
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025
2,Kedah,0.0,222.850,4238.00,579.090,0.0,0.0,0.0,5039.940,2025
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025
4,Kelantan,0.0,2322.990,1276.00,780.602,0.0,4.1,0.0,4383.692,2025

In [9]:
mapshaper_states = {
    'Johor': 'Johor', 
    'Kedah': 'Kedah', 
    'Kelantan': 'Kelantan', 
    'Melaka': 'Melaka', 
    'Negeri Sembilan': 'Negeri Sembilan', 
    'Pahang': 'Pahang', 
    'Pulau Pinang': 'Pulau Pinang', 
    'Perak': 'Perak', 
    'Perlis': 'Perlis', 
    'Selangor': 'Selangor', 
    'Terengganu': 'Terengganu', 
    'Sabah': 'Sabah', 
    'Sarawak': 'Sarawak', 
    'W.P. Kuala Lumpur': 'Kuala Lumpur', 
    'W.P. Putrajaya': 'Putrajaya', 
    'W.P. Labuan': 'Labuan'
}

In [10]:
def clean_df(df):
    df = df.copy()
    df['State'] = df['State'].astype(str).str.strip().str.replace('\n', ' ')
    df['State'] = df['State'].map(mapshaper_states)
    df = df.dropna(subset=['State'])
    for col in category_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0).round(0).astype(int)
    return df

In [11]:
df_2024 = clean_df(df_2024)
df_2025 = clean_df(df_2025)

In [16]:
cleaned_df = pd.concat([df_2024, df_2025], ignore_index=True)
cleaned_df = cleaned_df[['State', 'Year'] + category_cols]

In [18]:
cleaned_df['State_Year'] = cleaned_df['State'] + '_' + cleaned_df['Year'].astype(str)

In [19]:
cleaned_df.to_csv("cleaned_floodloss_agricultural.csv", index=False)