In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("SPECIAL REPORT ON IMPACT OF FLOODS IN MALAYSIA, 2025.xlsx", sheet_name="Jadual 1",skiprows=9)
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,Johor,NaN,1017727.0,NaN,21280.371206,26188.954000,NaN,2072.354552,874.052960,...,NaN,NaN,2432.790120,13010.384,NaN,29748.44675,29842.57674,NaN,58967.817028,72059.356700
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Kedah,NaN,528228.0,NaN,54013.122000,9773.938000,NaN,2094.910000,416.705000,...,NaN,NaN,118210.030000,5039.940,NaN,15052.90372,20113.41920,NaN,193662.168720,36665.527200
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Kelantan,NaN,363251.0,NaN,139014.917960,15617.649956,NaN,3984.363746,497.972317,...,NaN,NaN,43788.085926,4383.692,NaN,48088.78885,67139.93187,NaN,263033.339482,88538.011143

In [3]:
category_cols = ['Living Quarters', 'Vehicles', 'Business Premisses', 'Manufacturing', 'Agriculture', 'Infrastructure', 'Total Loss']

In [4]:
cols_2024 = [1, 5, 8, 11, 14, 17, 20, 23]
cols_2025 = [1,6,9,12,15,18,21,24]

In [5]:
df_2024 = df.iloc[:, cols_2024].copy()
df_2024.columns = ['State'] + category_cols
df_2024['Year'] = 2024

In [6]:
df_2025 = df.iloc[:, cols_2025].copy()
df_2025.columns = ['State'] + category_cols
df_2025['Year'] = 2025

In [7]:
mapshaper_states = {
    'Johor': 'Johor', 
    'Kedah': 'Kedah', 
    'Kelantan': 'Kelantan', 
    'Melaka': 'Melaka', 
    'Negeri Sembilan': 'Negeri Sembilan', 
    'Pahang': 'Pahang', 
    'Pulau Pinang': 'Pulau Pinang', 
    'Perak': 'Perak', 
    'Perlis': 'Perlis', 
    'Selangor': 'Selangor', 
    'Terengganu': 'Terengganu', 
    'Sabah': 'Sabah', 
    'Sarawak': 'Sarawak', 
    'W.P. Kuala Lumpur': 'Kuala Lumpur', 
    'W.P. Putrajaya': 'Putrajaya', 
    'W.P. Labuan': 'Labuan'
}

In [8]:
def clean_df (df):
    df=df.copy()
    df['State'] = df['State'].astype(str).str.strip().str.replace('\n', ' ')
    df['State'] = df['State'].map(mapshaper_states)
    df = df.dropna(subset=['State'])
    for col in category_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0).round(0).astype(int)
    return df

In [9]:
df_2024 = clean_df(df_2024)
df_2025 = clean_df(df_2025)

In [10]:
cleaned_df = pd.concat([df_2024, df_2025], ignore_index=True)
cleaned_df = cleaned_df[['State', 'Year'] + category_cols]

In [11]:
cleaned_df['State_Year'] = cleaned_df['State'] + '_' + cleaned_df['Year'].astype(str)

In [12]:
cleaned_df.head()

,State,Year,Living Quarters,Vehicles,Business Premisses,Manufacturing,Agriculture,Infrastructure,Total Loss,State_Year
0,Johor,2024,21280,2072,3434,0,2433,29748,58968,Johor_2024
1,Kedah,2024,54013,2095,4291,0,118210,15053,193662,Kedah_2024
2,Kelantan,2024,139015,3984,27066,1091,43788,48089,263033,Kelantan_2024
3,Melaka,2024,1048,82,63,0,472,7249,8913,Melaka_2024
4,Negeri Sembilan,2024,2922,77,62,0,1210,16180,20451,Negeri Sembilan_2024

In [13]:
cleaned_df.to_csv("cleaned_floodloss_all.csv", index=False)